package com.example.srikant.apishitting.home.java_model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDetailsDaoConfig;
    private final DaoConfig locationDbModelDaoConfig;

    private final UserDetailsDao userDetailsDao;
    private final LocationDbModelDao locationDbModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDetailsDaoConfig = daoConfigMap.get(UserDetailsDao.class).clone();
        userDetailsDaoConfig.initIdentityScope(type);

        locationDbModelDaoConfig = daoConfigMap.get(LocationDbModelDao.class).clone();
        locationDbModelDaoConfig.initIdentityScope(type);

        userDetailsDao = new UserDetailsDao(userDetailsDaoConfig, this);
        locationDbModelDao = new LocationDbModelDao(locationDbModelDaoConfig, this);

        registerDao(UserDetails.class, userDetailsDao);
        registerDao(LocationDbModel.class, locationDbModelDao);
    }
    
    public void clear() {
        userDetailsDaoConfig.clearIdentityScope();
        locationDbModelDaoConfig.clearIdentityScope();
    }

    public UserDetailsDao getUserDetailsDao() {
        return userDetailsDao;
    }

    public LocationDbModelDao getLocationDbModelDao() {
        return locationDbModelDao;
    }

}
